language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7
          env: deps=low
        - php: 7
    fast_finish: true

env:
  - CALCULATOR=GMP
  - CALCULATOR=BCMath
  - CALCULATOR=Native

before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi

script: bin/phpspec run -f pretty --verbose

notifications:
    email: "alex@rhetina.com"
