language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - hhvm

env:
  - CALCULATOR=GMP
  - CALCULATOR=BCMath
  - CALCULATOR=Native

before_script: composer update --prefer-dist

script: bin/phpspec run -f pretty --verbose

notifications:
    email: "alex@rhetina.com"
