language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - CALCULATOR=GMP
  - CALCULATOR=BCMath
  - CALCULATOR=Native

before_script: composer install --dev --prefer-source

script: bin/phpspec run -f pretty --verbose

notifications:
    email: "alex@rhetina.com"
